version: "3.1"

recipe: default.v1

language: en

pipeline:
# Tokenization
- name: WhitespaceTokenizer
- name: RegexFeaturizer  # Changed from RegexTokenizer to RegexFeaturizer

# Language Model
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "rasa/LaBSE"
  cache_dir: null

# Character-level features for multilingual support
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

# Intent Classification
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax
  intent_classification: true
  entity_recognition: true
  use_masked_language_model: true
  BILOU_flag: true

# Entity Extraction  
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax

# Fallback
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 200
  constrain_similarities: true
assistant_id: 20250805-204613-product-search